dist: xenial   # required for Python >= 3.7

sudo: false

language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-django20
    - python: 3.6
      env: TOXENV=py36-django21
    - python: 3.6
      env: TOXENV=py36-django22
    - python: 3.7
      env: TOXENV=py37-django20
    - python: 3.7
      env: TOXENV=py37-django21
    - python: 3.7
      env: TOXENV=py37-django22

install:
  - pip install tox tox-travis coveralls

script:
  - tox

after_success:
  - coveralls