sudo: no

language: python

env:
  - TOXENV=flake8
  - TOXENV=py27-django111
  - TOXENV=py27-django20
  - TOXENV=py27-django21
  - TOXENV=py27-django22
  - TOXENV=py36-django111
  - TOXENV=py36-django20
  - TOXENV=py36-django21
  - TOXENV=py36-django22
  - TOXENV=py37-django111
  - TOXENV=py37-django20
  - TOXENV=py37-django21
  - TOXENV=py37-django22

install:
  - pip install tox coveralls

script:
  - tox

after_success:
  - coveralls